### ISSUE TITLE
Patching of bsv files fails if the project uses bsv2

### ISSUE THREAD

**Issue by torusJKL** [sCrypt-Inc/scryptlib#155]
When bsv2 is used as the bsv library in packages.json than npm installs the bsv1 files locally within the scryptlib node_modules folder.
The post install assumes the project is using bsv 1 and tries to patch files that do not exist at the expected location.

Error by npm i:
```
scryptlib@0.10.3 postinstall /home/torus/src/test/node_modules/scryptlib
node patches/applyPatch.js

Error: ENOENT: no such file or directory, copyfile '/home/torus/src/test/node_modules/scryptlib/patches/bsv/lib/crypto/bn.js' -> '/home/torus/src/test/node_modules/bsv/lib/crypto/bn.js'
    at copyFileSync (fs.js:2061:3)
    at /home/torus/src/test/node_modules/scryptlib/patches/applyPatch.js:30:9
    at Array.map (<anonymous>)
    at apply (/home/torus/src/test/node_modules/scryptlib/patches/applyPatch.js:21:13)
    at Object.<anonymous> (/home/torus/src/test/node_modules/scryptlib/patches/applyPatch.js:56:5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  errno: -2,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: '/home/torus/src/test/node_modules/scryptlib/patches/bsv/lib/crypto/bn.js',
  dest: '/home/torus/src/test/node_modules/bsv/lib/crypto/bn.js'
`}
```

**Comment by torusJKL** [comment]
bsv2 seems to be abandoned and I don't use it anymore.
